# proto-file: goto.proto
# proto-name: everchanging.goto.Config

default_url: "https://everchanging.dev"

links {
  links_by_group {
    key: "projects"
    value {
      links_by_group {
        key: "goto"
        value {
          url: "https://github.com/directed-graph/goto"
        }
      }
      links_by_group {
        key: "symfs"
        value {
          url: "https://github.com/directed-graph/symfs"
        }
      }
    }
  }
  links_by_group {
    key: "ins"
    value {
      links_by_group {
        key: "bike"
        value {
          url: "https://www.instagram.com/p/CkTs9pIP9iI/"
        }
      }
      links_by_group {
        key: "holo"
        value {
          url: "https://www.instagram.com/p/CkB_3ZcSV-A/"
        }
      }
      links_by_group {
        key: "steak"
        value {
          url: "https://www.instagram.com/p/CmSmaGHpUDD/"
        }
      }
    }
  }
  links_by_group {
    key: "profiles"
    value {
      links_by_group {
        key: "github"
        value {
          url: "https://github.com/directed-graph"
        }
      }
      links_by_group {
        key: "instagram"
        value {
          url: "https://www.instagram.com/instant_analog/"
        }
      }
      links_by_group {
        key: "strava"
        value {
          url: "https://www.strava.com/athletes/108546168"
        }
      }
    }
  }
}

