# proto-file: goto.proto
# proto-name: everchanging.goto.Config

default_url: "https://everchanging.dev"

links {
  links_by_group {
    key: "projects"
    value {
      links_by_group {
        key: "goto"
        value {
          url: "https://github.com/directed-graph/goto"
        }
      }
    }
  }
  links_by_group {
    key: "ins"
    value {
      links_by_group {
        key: "bike"
        value {
          url: "https://www.instagram.com/p/CkTs9pIP9iI/"
        }
      }
      links_by_group {
        key: "holo"
        value {
          url: "https://www.instagram.com/p/CkB_3ZcSV-A/"
        }
      }
    }
  }
}

